### PR TITLE
fix: add guard before sanitizing

### LINKED ISSUE #7: Extend security for unfiltered html cap to premium actions

### PR DESCRIPTION
**Pull request by Arukuen**
fixes #7

## Summary by CodeRabbit

* **New Features**
  * Comprehensive input sanitization and permission-aware validation for interactive actions; editor now shows restriction notices when applicable; post-update cache invalidation.

* **Documentation**
  * Readme expanded with guides, examples, pricing info, Learn more links, screenshots, and source code reference.

* **Chores**
  * Version bumped to 1.3.2; CI triggers updated; packaging/packager behavior and build metadata enhancements; editor localization now exposes permission flag.

* **Style**
  * VSCode search settings adjusted to include a new pattern.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/action-types/class-action-type-toggle-class.php [hunk 1]
```diff
@@ -35,21 +35,36 @@ public function initialize() {
...
 			];
 
 			$this->has_starting_state = false;
 			$this->has_duration = false;
 			$this->has_easing = false;
 		}
+
+		public function sanitize_data_for_saving( $value ) {
+			if ( is_array( $value ) && isset( $value['class'] ) ) {
+				$value['class'] = sanitize_key( $value['class'] );
```
Comment (bfintal) [inline src/action-types/class-action-type-toggle-class.php]:
```suggestion
				$value['class'] = sanitize_html_class( $value['class'] );
```
